"""Remove module_id from permissions and make permissions global

Revision ID: af495a48b1f1
Revises: 5ecab67f91d9
Create Date: 2025-07-28 13:00:17.669471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af495a48b1f1'
down_revision: Union[str, Sequence[str], None] = '5ecab67f91d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
