"""Set ON DELETE SET NULL on assigned_by

Revision ID: c00dcc17d67d
Revises: 3957fdf5892d
Create Date: 2025-08-04 14:03:36.310820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c00dcc17d67d'
down_revision: Union[str, Sequence[str], None] = '3957fdf5892d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_permissions_assigned_by_fkey'), 'user_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'user_permissions', 'users', ['assigned_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('users_created_by_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_created_by_fkey'), 'users', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'user_permissions', type_='foreignkey')
    op.create_foreign_key(op.f('user_permissions_assigned_by_fkey'), 'user_permissions', 'users', ['assigned_by'], ['id'])
    # ### end Alembic commands ###
