"""Remove module_id from permissions and make permissions global

Revision ID: 5ecab67f91d9
Revises: 8a5ee70674ed
Create Date: 2025-07-28 12:59:29.039440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ecab67f91d9'
down_revision: Union[str, Sequence[str], None] = '8a5ee70674ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('_module_action_uc'), 'permissions', type_='unique')
    op.create_unique_constraint(None, 'permissions', ['action'])
    op.drop_constraint(op.f('permissions_module_id_fkey'), 'permissions', type_='foreignkey')
    op.drop_column('permissions', 'module_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('module_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('permissions_module_id_fkey'), 'permissions', 'modules', ['module_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'permissions', type_='unique')
    op.create_unique_constraint(op.f('_module_action_uc'), 'permissions', ['module_id', 'action'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
