"""Remove module_id from permissions and make permissions global

Revision ID: 6fcce57c3bc9
Revises: c02907918e84
Create Date: 2025-07-28 12:40:09.091083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fcce57c3bc9'
down_revision: Union[str, Sequence[str], None] = 'c02907918e84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
