"""Make module_id nullable in permissions

Revision ID: 8a5ee70674ed
Revises: e1b81aefe3e1
Create Date: 2025-07-28 12:45:34.209195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a5ee70674ed'
down_revision: Union[str, Sequence[str], None] = 'e1b81aefe3e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('permissions', 'module_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('permissions', 'module_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
