"""Remove module_id from permissions and make permissions global

Revision ID: e1b81aefe3e1
Revises: 6fcce57c3bc9
Create Date: 2025-07-28 12:43:19.122245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1b81aefe3e1'
down_revision: Union[str, Sequence[str], None] = '6fcce57c3bc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
